title: WebDevelopment
author: Pragyamittal0
email: pragya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It will help you to start with WebDevelopment
theme: minima

# social links
github_username:  pragyamittal0 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
